# Generated by Django 4.1.3 on 2022-12-08 08:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='paid',
            new_name='is_paid',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='Product',
            new_name='product_id',
        ),
    ]
