# Generated by Django 4.1.3 on 2022-12-07 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='ratings',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
